# Generated by Django 6.0.4 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0070_preserve_annotations_when_article_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("nord", "Nord"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme_light",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("nord", "Nord"),
                ],
                default="light",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme_dark",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("nord", "Nord"),
                ],
                default="dark",
                max_length=10,
            ),
        ),
    ]
