# Generated by Django 6.1 on 2026-09-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0094_add_asset_scheduling_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='health_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='health_status',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('ok', 'Ok'), ('dead', 'Dead'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('missing', 'Missing'), ('unknown', 'Unknown')], db_index=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='CheckJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('interrupted', 'Interrupted'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('total', models.IntegerField(default=0)),
                ('done', models.IntegerField(default=0)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('paused_sec', models.IntegerField(default=0)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_max_age_days',
            field=models.IntegerField(blank=True, default=None, help_text='How many days a health check result stays valid before it is considered expired. Leave empty to use the global default (LINK_HEALTH_MAX_AGE_DAYS, default 15).', null=True, verbose_name='Result validity (days)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_check_workers',
            field=models.IntegerField(blank=True, default=None, help_text='Number of parallel health check workers. Leave empty to use the global default (LD_HEALTH_CHECK_WORKERS, default 8).', null=True, verbose_name='Check concurrency'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_domain_interval',
            field=models.FloatField(blank=True, default=None, help_text='Minimum interval between requests to the same domain. Leave empty to use the global default (LD_METADATA_DOMAIN_COOLDOWN_SEC).', null=True, verbose_name='Per-domain interval (seconds)'),
        ),
    ]
