# Generated by Django 6.1 on 2026-09-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0095_bookmark_health_check"),
        ("bookmarks", "0096_alter_userprofile_theme_choices"),
    ]

    operations = []
