name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/default.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            jcbl1/linkding-cn:latest
            jcbl1/linkding-cn:${{ env.VERSION }}
            ghcr.io/jcbl1/linkding-cn:latest
            ghcr.io/jcbl1/linkding-cn:${{ env.VERSION }}
          target: linkding
          build-args: |
            UV_INDEX_URL=https://pypi.org/simple
          push: true

      - name: Build latest-alpine
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            jcbl1/linkding-cn:latest-alpine
            jcbl1/linkding-cn:${{ env.VERSION }}-alpine
            ghcr.io/jcbl1/linkding-cn:latest-alpine
            ghcr.io/jcbl1/linkding-cn:${{ env.VERSION }}-alpine
          target: linkding
          build-args: |
            UV_INDEX_URL=https://pypi.org/simple
          push: true

      - name: Build latest-plus
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/default.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            jcbl1/linkding-cn:latest-plus
            jcbl1/linkding-cn:${{ env.VERSION }}-plus
            ghcr.io/jcbl1/linkding-cn:latest-plus
            ghcr.io/jcbl1/linkding-cn:${{ env.VERSION }}-plus
          target: linkding-plus
          build-args: |
            UV_INDEX_URL=https://pypi.org/simple
          push: true

      - name: Build latest-plus-alpine
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            jcbl1/linkding-cn:latest-plus-alpine
            jcbl1/linkding-cn:${{ env.VERSION }}-plus-alpine
            ghcr.io/jcbl1/linkding-cn:latest-plus-alpine
            ghcr.io/jcbl1/linkding-cn:${{ env.VERSION }}-plus-alpine
          target: linkding-plus
          build-args: |
            UV_INDEX_URL=https://pypi.org/simple
          push: true