name: linkding CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.20.0"
          cache: 'npm'
      - name: Install Node dependencies
        run: npm ci
      - name: Setup Python environment
        run: |
          uv sync --locked
          mkdir -p data
      - name: Validate build tooling
        run: |
          python3 -m unittest discover -s scripts/tests -v
      - name: Compile translations
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          uv run manage.py compilemessages --ignore=.venv --ignore=node_modules
      - name: Run tests
        run: uv run pytest bookmarks/tests/ site_adapters/tests/ -n auto
  e2e_tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.20.0"
          cache: 'npm'
      - name: Install Node dependencies
        run: npm ci
      - name: Setup Python environment
        run: |
          uv sync --locked
          uv run playwright install chromium
          mkdir -p data
      - name: Run build
        run: |
          npm run build
          uv run manage.py collectstatic
      - name: Run tests
        run: uv run manage.py test bookmarks.tests_e2e --pattern="e2e_test_*.py"

  images:
    name: Release image validation
    uses: ./.github/workflows/image-validation.yaml
